package cn.njcit.dao;

import cn.njcit.mapper.model.Report;
import cn.njcit.mapper.model.ReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    int countByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    int deleteByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    int deleteByPrimaryKey(Integer reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    int insertSelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    List<Report> selectByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    Report selectByPrimaryKey(Integer reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    int updateByExample(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    int updateByPrimaryKeySelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    int updateByPrimaryKey(Report record);
}