server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://47.95.231.218:3306/competition_db?characterEncoding=utf-8&useSSL=false
        username: root
        password: Hu123321..
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
        # 是否开启模板缓存，默认true
        cache: true
        #spring.thymeleaf.check-template-location=true
        check-template-location: true
        # Content-Type value
        content-type: text/html
        # 是否启用MVC-Thymeleaf视图
        enabled: true
        # 模板编码
        encoding: utf-8
        #应该从解析中排除的视图名称列表（用逗号分隔）
        excluded-view-names:
        # 要应用于模板的模板模式。另请参见StandardTemplateModeHandlers。
        mode: HTML5
        # 在链接网址时预先查看名称的前缀。
        prefix: classpath:/templates/
        # 链接网址时附加到视图名称的后缀。
        suffix: .html
        # 指定模板的解析顺序，默认为第一个.
        template-resolver-order:
        # 指定使用模板的视图名，多个以逗号分隔
        view-names:
    #上传文件内存占用限制
    http:
      multipart:
        max-file-size: 100MB
        max-request-size: 500MB
mybatis: 
    mapperLocations: classpath:cn/njcit/mapper/*.xml
    typeAliasesPackage: cn.njcit.mapper.model 
    #pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql