package cn.njcit.mapper.model;

import java.util.Date;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_id
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private Integer newsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_title
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String newsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_column
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String newsColumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_content
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String newsContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.create_time
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.update_time
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_id
     *
     * @return the value of news.news_id
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_id
     *
     * @param newsId the value for news.news_id
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_title
     *
     * @return the value of news.news_title
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_title
     *
     * @param newsTitle the value for news.news_title
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_column
     *
     * @return the value of news.news_column
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getNewsColumn() {
        return newsColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_column
     *
     * @param newsColumn the value for news.news_column
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setNewsColumn(String newsColumn) {
        this.newsColumn = newsColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_content
     *
     * @return the value of news.news_content
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getNewsContent() {
        return newsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_content
     *
     * @param newsContent the value for news.news_content
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.create_time
     *
     * @return the value of news.create_time
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.create_time
     *
     * @param createTime the value for news.create_time
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.update_time
     *
     * @return the value of news.update_time
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.update_time
     *
     * @param updateTime the value for news.update_time
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}