package cn.njcit.mapper.model;

import java.util.Date;

public class Report {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.report_id
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private Integer reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.main_student_no
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String mainStudentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.main_student_name
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String mainStudentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.main_student_specialty
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String mainStudentSpecialty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.main_student_phone
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String mainStudentPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.main_student_email
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String mainStudentEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.main_student_department
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String mainStudentDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.main_student_grade
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String mainStudentGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.main_student_QQ
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String mainStudentQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student1_no
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String student1No;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student1_name
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String student1Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student1_specialty
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String student1Specialty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student1_phone
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String student1Phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student1_email
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String student1Email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student1_department
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String student1Department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student1_grade
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String student1Grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student1_QQ
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String student1Qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student2_no
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String student2No;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student2_name
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String student2Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student2_specialty
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String student2Specialty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student2_phone
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String student2Phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student2_email
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String student2Email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student2_department
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String student2Department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student2_grade
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String student2Grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student2_QQ
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String student2Qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.teacher_name
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.teacher_phone
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String teacherPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.teacher_email
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String teacherEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.teacher_department
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String teacherDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.teacher_QQ
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String teacherQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.works_no
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String worksNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.works_name
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private String worksName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.create_time
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.update_time
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.report_id
     *
     * @return the value of report.report_id
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public Integer getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.report_id
     *
     * @param reportId the value for report.report_id
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.main_student_no
     *
     * @return the value of report.main_student_no
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getMainStudentNo() {
        return mainStudentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.main_student_no
     *
     * @param mainStudentNo the value for report.main_student_no
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setMainStudentNo(String mainStudentNo) {
        this.mainStudentNo = mainStudentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.main_student_name
     *
     * @return the value of report.main_student_name
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getMainStudentName() {
        return mainStudentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.main_student_name
     *
     * @param mainStudentName the value for report.main_student_name
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setMainStudentName(String mainStudentName) {
        this.mainStudentName = mainStudentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.main_student_specialty
     *
     * @return the value of report.main_student_specialty
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getMainStudentSpecialty() {
        return mainStudentSpecialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.main_student_specialty
     *
     * @param mainStudentSpecialty the value for report.main_student_specialty
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setMainStudentSpecialty(String mainStudentSpecialty) {
        this.mainStudentSpecialty = mainStudentSpecialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.main_student_phone
     *
     * @return the value of report.main_student_phone
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getMainStudentPhone() {
        return mainStudentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.main_student_phone
     *
     * @param mainStudentPhone the value for report.main_student_phone
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setMainStudentPhone(String mainStudentPhone) {
        this.mainStudentPhone = mainStudentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.main_student_email
     *
     * @return the value of report.main_student_email
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getMainStudentEmail() {
        return mainStudentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.main_student_email
     *
     * @param mainStudentEmail the value for report.main_student_email
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setMainStudentEmail(String mainStudentEmail) {
        this.mainStudentEmail = mainStudentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.main_student_department
     *
     * @return the value of report.main_student_department
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getMainStudentDepartment() {
        return mainStudentDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.main_student_department
     *
     * @param mainStudentDepartment the value for report.main_student_department
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setMainStudentDepartment(String mainStudentDepartment) {
        this.mainStudentDepartment = mainStudentDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.main_student_grade
     *
     * @return the value of report.main_student_grade
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getMainStudentGrade() {
        return mainStudentGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.main_student_grade
     *
     * @param mainStudentGrade the value for report.main_student_grade
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setMainStudentGrade(String mainStudentGrade) {
        this.mainStudentGrade = mainStudentGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.main_student_QQ
     *
     * @return the value of report.main_student_QQ
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getMainStudentQq() {
        return mainStudentQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.main_student_QQ
     *
     * @param mainStudentQq the value for report.main_student_QQ
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setMainStudentQq(String mainStudentQq) {
        this.mainStudentQq = mainStudentQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student1_no
     *
     * @return the value of report.student1_no
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getStudent1No() {
        return student1No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student1_no
     *
     * @param student1No the value for report.student1_no
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setStudent1No(String student1No) {
        this.student1No = student1No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student1_name
     *
     * @return the value of report.student1_name
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getStudent1Name() {
        return student1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student1_name
     *
     * @param student1Name the value for report.student1_name
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setStudent1Name(String student1Name) {
        this.student1Name = student1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student1_specialty
     *
     * @return the value of report.student1_specialty
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getStudent1Specialty() {
        return student1Specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student1_specialty
     *
     * @param student1Specialty the value for report.student1_specialty
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setStudent1Specialty(String student1Specialty) {
        this.student1Specialty = student1Specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student1_phone
     *
     * @return the value of report.student1_phone
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getStudent1Phone() {
        return student1Phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student1_phone
     *
     * @param student1Phone the value for report.student1_phone
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setStudent1Phone(String student1Phone) {
        this.student1Phone = student1Phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student1_email
     *
     * @return the value of report.student1_email
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getStudent1Email() {
        return student1Email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student1_email
     *
     * @param student1Email the value for report.student1_email
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setStudent1Email(String student1Email) {
        this.student1Email = student1Email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student1_department
     *
     * @return the value of report.student1_department
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getStudent1Department() {
        return student1Department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student1_department
     *
     * @param student1Department the value for report.student1_department
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setStudent1Department(String student1Department) {
        this.student1Department = student1Department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student1_grade
     *
     * @return the value of report.student1_grade
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getStudent1Grade() {
        return student1Grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student1_grade
     *
     * @param student1Grade the value for report.student1_grade
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setStudent1Grade(String student1Grade) {
        this.student1Grade = student1Grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student1_QQ
     *
     * @return the value of report.student1_QQ
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getStudent1Qq() {
        return student1Qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student1_QQ
     *
     * @param student1Qq the value for report.student1_QQ
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setStudent1Qq(String student1Qq) {
        this.student1Qq = student1Qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student2_no
     *
     * @return the value of report.student2_no
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getStudent2No() {
        return student2No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student2_no
     *
     * @param student2No the value for report.student2_no
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setStudent2No(String student2No) {
        this.student2No = student2No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student2_name
     *
     * @return the value of report.student2_name
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getStudent2Name() {
        return student2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student2_name
     *
     * @param student2Name the value for report.student2_name
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setStudent2Name(String student2Name) {
        this.student2Name = student2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student2_specialty
     *
     * @return the value of report.student2_specialty
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getStudent2Specialty() {
        return student2Specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student2_specialty
     *
     * @param student2Specialty the value for report.student2_specialty
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setStudent2Specialty(String student2Specialty) {
        this.student2Specialty = student2Specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student2_phone
     *
     * @return the value of report.student2_phone
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getStudent2Phone() {
        return student2Phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student2_phone
     *
     * @param student2Phone the value for report.student2_phone
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setStudent2Phone(String student2Phone) {
        this.student2Phone = student2Phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student2_email
     *
     * @return the value of report.student2_email
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getStudent2Email() {
        return student2Email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student2_email
     *
     * @param student2Email the value for report.student2_email
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setStudent2Email(String student2Email) {
        this.student2Email = student2Email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student2_department
     *
     * @return the value of report.student2_department
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getStudent2Department() {
        return student2Department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student2_department
     *
     * @param student2Department the value for report.student2_department
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setStudent2Department(String student2Department) {
        this.student2Department = student2Department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student2_grade
     *
     * @return the value of report.student2_grade
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getStudent2Grade() {
        return student2Grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student2_grade
     *
     * @param student2Grade the value for report.student2_grade
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setStudent2Grade(String student2Grade) {
        this.student2Grade = student2Grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student2_QQ
     *
     * @return the value of report.student2_QQ
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getStudent2Qq() {
        return student2Qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student2_QQ
     *
     * @param student2Qq the value for report.student2_QQ
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setStudent2Qq(String student2Qq) {
        this.student2Qq = student2Qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.teacher_name
     *
     * @return the value of report.teacher_name
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.teacher_name
     *
     * @param teacherName the value for report.teacher_name
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.teacher_phone
     *
     * @return the value of report.teacher_phone
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getTeacherPhone() {
        return teacherPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.teacher_phone
     *
     * @param teacherPhone the value for report.teacher_phone
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setTeacherPhone(String teacherPhone) {
        this.teacherPhone = teacherPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.teacher_email
     *
     * @return the value of report.teacher_email
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getTeacherEmail() {
        return teacherEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.teacher_email
     *
     * @param teacherEmail the value for report.teacher_email
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setTeacherEmail(String teacherEmail) {
        this.teacherEmail = teacherEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.teacher_department
     *
     * @return the value of report.teacher_department
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getTeacherDepartment() {
        return teacherDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.teacher_department
     *
     * @param teacherDepartment the value for report.teacher_department
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setTeacherDepartment(String teacherDepartment) {
        this.teacherDepartment = teacherDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.teacher_QQ
     *
     * @return the value of report.teacher_QQ
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getTeacherQq() {
        return teacherQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.teacher_QQ
     *
     * @param teacherQq the value for report.teacher_QQ
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setTeacherQq(String teacherQq) {
        this.teacherQq = teacherQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.works_no
     *
     * @return the value of report.works_no
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getWorksNo() {
        return worksNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.works_no
     *
     * @param worksNo the value for report.works_no
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setWorksNo(String worksNo) {
        this.worksNo = worksNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.works_name
     *
     * @return the value of report.works_name
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public String getWorksName() {
        return worksName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.works_name
     *
     * @param worksName the value for report.works_name
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setWorksName(String worksName) {
        this.worksName = worksName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.create_time
     *
     * @return the value of report.create_time
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.create_time
     *
     * @param createTime the value for report.create_time
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.update_time
     *
     * @return the value of report.update_time
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.update_time
     *
     * @param updateTime the value for report.update_time
     *
     * @mbggenerated Tue Mar 06 21:15:55 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}